FROM mcr.microsoft.com/playwright:v1.61.1-noble

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm exec esbuild src/server/index.ts --bundle --platform=node --outfile=dist/server/index.js --format=esm --packages=external

CMD ["pnpm", "exec", "playwright", "test"]
