# fly.toml app configuration file generated for matchmaking-survey on 2026-07-10T10:15:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'matchmaking-survey'
primary_region = 'lhr'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '256mb'
cpus = 1
memory_mb = 256

[mounts]
source = "matchmaking_survey"
destination = "/data"
